USE `CommunEvent`;

-- Owner (35 rows)
INSERT INTO Owner (FName, LName, DOB, Email) VALUES
('Margaret', 'Holloway', '1975-04-12', 'margaret.holloway@email.com'),
('Carlos', 'Reyes', '1982-09-28', 'carlos.reyes@email.com'),
('Linda', 'Nakamura', '1968-11-03', 'linda.nakamura@email.com'),
('Thomas', 'Brennan', '1971-06-17', 'thomas.brennan@email.com'),
('Patricia', 'Sullivan', '1965-02-25', 'patricia.sullivan@email.com'),
('David', 'Fitzgerald', '1978-08-09', 'david.fitzgerald@email.com'),
('Helen', 'Nguyen', '1980-03-14', 'helen.nguyen@email.com'),
('Robert', 'Marconi', '1963-12-30', 'robert.marconi@email.com'),
('Angela', 'Petrov', '1985-07-21', 'angela.petrov@email.com'),
('James', 'Okafor', '1970-10-05', 'james.okafor@email.com'),
('Susan', 'Kowalski', '1969-01-19', 'susan.kowalski@email.com'),
('Michael', 'Andrade', '1974-05-08', 'michael.andrade@email.com'),
('Claire', 'Bernstein', '1983-09-11', 'claire.bernstein@email.com'),
('George', 'Tran', '1961-04-23', 'george.tran@email.com'),
('Nancy', 'O''Brien', '1977-11-16', 'nancy.obrien@email.com'),
('Richard', 'Chakraborty', '1972-07-04', 'richard.chakraborty@email.com'),
('Diane', 'Rosenberg', '1966-03-29', 'diane.rosenberg@email.com'),
('Kevin', 'MacLeod', '1981-08-18', 'kevin.macleod@email.com'),
('Laura', 'Ferreira', '1979-06-02', 'laura.ferreira@email.com'),
('Steven', 'Huang', '1967-12-13', 'steven.huang@email.com'),
('Barbara', 'Walsh', '1973-02-07', 'barbara.walsh@email.com'),
('William', 'Santos', '1984-10-27', 'william.santos@email.com'),
('Dorothy', 'Kim', '1976-05-31', 'dorothy.kim@email.com'),
('Edward', 'Patel', '1960-09-06', 'edward.patel@email.com'),
('Sandra', 'Johansson', '1988-01-24', 'sandra.johansson@email.com'),
('Paul', 'Moran', '1964-07-15', 'paul.moran@email.com'),
('Christine', 'Delacroix', '1987-04-03', 'christine.delacroix@email.com'),
('Kenneth', 'Adeyemi', '1969-11-22', 'kenneth.adeyemi@email.com'),
('Sharon', 'Vasquez', '1975-08-10', 'sharon.vasquez@email.com'),
('Brian', 'Liang', '1982-03-17', 'brian.liang@email.com'),
('Donna', 'McCarthy', '1971-06-28', 'donna.mccarthy@email.com'),
('Gregory', 'Esposito', '1977-09-04', 'gregory.esposito@email.com'),
('Michelle', 'Cohen', '1986-12-19', 'michelle.cohen@email.com'),
('Raymond', 'Oluwole', '1963-05-14', 'raymond.oluwole@email.com'),
('Janet', 'Yamamoto', '1980-01-08', 'janet.yamamoto@email.com');

-- Organizer (35 rows)
INSERT INTO Organizer (FName, LName, Email, Location) VALUES
('Jordan', 'Blake', 'jordan.blake@events.com', 'Boston, MA'),
('Priya', 'Sharma', 'priya.sharma@events.com', 'Cambridge, MA'),
('Marcus', 'Webb', 'marcus.webb@events.com', 'Somerville, MA'),
('Alicia', 'Fontaine', 'alicia.fontaine@events.com', 'Boston, MA'),
('Derek', 'Quinlan', 'derek.quinlan@events.com', 'Brookline, MA'),
('Tanya', 'Morrison', 'tanya.morrison@events.com', 'Jamaica Plain, MA'),
('Owen', 'Fitzgerald', 'owen.fitzgerald@events.com', 'Boston, MA'),
('Rachel', 'Stern', 'rachel.stern@events.com', 'Allston, MA'),
('Brendan', 'Park', 'brendan.park@events.com', 'Cambridge, MA'),
('Simone', 'Duval', 'simone.duval@events.com', 'Boston, MA'),
('Tyler', 'Nakashima', 'tyler.nakashima@events.com', 'Fenway, MA'),
('Fatima', 'Hassan', 'fatima.hassan@events.com', 'Roxbury, MA'),
('Colin', 'Murray', 'colin.murray@events.com', 'Charlestown, MA'),
('Ingrid', 'Sorensen', 'ingrid.sorensen@events.com', 'South End, MA'),
('Darnell', 'Washington', 'darnell.washington@events.com', 'Dorchester, MA'),
('Mei', 'Lin', 'mei.lin@events.com', 'Quincy, MA'),
('Patrick', 'Donnelly', 'patrick.donnelly@events.com', 'Newton, MA'),
('Zoe', 'Kantor', 'zoe.kantor@events.com', 'Waltham, MA'),
('Andre', 'Moreau', 'andre.moreau@events.com', 'Boston, MA'),
('Leah', 'Goldstein', 'leah.goldstein@events.com', 'Medford, MA'),
('Christopher', 'Otieno', 'christopher.otieno@events.com', 'Malden, MA'),
('Sofia', 'Castillo', 'sofia.castillo@events.com', 'East Boston, MA'),
('Nathan', 'Hooper', 'nathan.hooper@events.com', 'Brighton, MA'),
('Amara', 'Diallo', 'amara.diallo@events.com', 'Boston, MA'),
('Ryan', 'Callahan', 'ryan.callahan@events.com', 'Somerville, MA'),
('Yuki', 'Tanaka', 'yuki.tanaka@events.com', 'Cambridge, MA'),
('Jasmine', 'Reid', 'jasmine.reid@events.com', 'Boston, MA'),
('Felipe', 'Rojas', 'felipe.rojas@events.com', 'Jamaica Plain, MA'),
('Hannah', 'Schwartz', 'hannah.schwartz@events.com', 'Brookline, MA'),
('Marcus', 'Osei', 'marcus.osei@events.com', 'Boston, MA'),
('Nadia', 'Petrov', 'nadia.petrov@events.com', 'Back Bay, MA'),
('Eli', 'Cohen', 'eli.cohen@events.com', 'Cambridge, MA'),
('Vera', 'Kowalski', 'vera.kowalski@events.com', 'Somerville, MA'),
('Troy', 'Baptiste', 'troy.baptiste@events.com', 'Boston, MA'),
('Iris', 'Huang', 'iris.huang@events.com', 'Newton, MA');


-- Performer (35 rows)
INSERT INTO Performer (FName, LName, Genre, Bio, MediaLinks, Availability, Views, Ranking) VALUES
('Sofia', 'Montez', 'Jazz', 'Award-winning jazz vocalist with 10 years of stage experience.', 'soundcloud.com/sofiamontez', 'Weekends', 14200, 4.80),
('Derek', 'Lund', 'Rock', 'Frontman of indie rock band The Static Owls.', 'spotify.com/thestaticowls', 'Flexible', 8900, 4.30),
('Amara', 'Osei', 'Classical', 'Classically trained pianist and composer based in Boston.', 'youtube.com/amaraosei', 'Weekdays', 21000, 4.90),
('Caleb', 'Kim', 'Indie Pop', 'Boston-based indie artist with 5 years of live performance experience.', 'instagram.com/calebkimmusic', 'Weekends', 6300, 4.10),
('Nadia', 'Rivera', 'Hip-Hop', 'Lyricist and beatmaker from Roxbury with a growing local following.', 'soundcloud.com/nadiarivera', 'Flexible', 11500, 4.50),
('Finn', 'O''Sullivan', 'Folk', 'Irish folk singer-songwriter, regular at Cambridge open mics.', 'bandcamp.com/finnosullivan', 'Weekends', 5200, 4.00),
('Jasmine', 'Tran', 'R&B', 'Soulful R&B vocalist known for intimate live performances.', 'spotify.com/jasminetran', 'Flexible', 17800, 4.70),
('Leo', 'Marchetti', 'Electronic', 'DJ and producer specializing in house and techno.', 'soundcloud.com/leomarchetti', 'Weekends', 9400, 4.20),
('Priya', 'Kapoor', 'Classical', 'Violin soloist with the New England Conservatory.', 'youtube.com/priyakapoor', 'Weekdays', 23100, 4.95),
('Darius', 'Cole', 'Jazz', 'Saxophonist with 15 years of professional jazz performance.', 'spotify.com/dariuscole', 'Flexible', 16700, 4.75),
('Elena', 'Voss', 'Pop', 'Emerging pop singer-songwriter with catchy hooks and strong stage presence.', 'instagram.com/elenavossmusic', 'Weekends', 7800, 4.15),
('Marcus', 'Bell', 'Hip-Hop', 'Battle rapper turned conscious hip-hop artist from Dorchester.', 'youtube.com/marcusbell', 'Flexible', 12300, 4.55),
('Yuna', 'Choi', 'K-Pop Cover', 'K-pop dance and vocal cover performer, popular at cultural events.', 'tiktok.com/yunachoi', 'Weekends', 19500, 4.60),
('Brendan', 'Hayes', 'Comedy', 'Stand-up comedian performing across New England venues.', 'instagram.com/brendanhayes', 'Flexible', 8100, 4.25),
('Chloe', 'Dupont', 'Dance', 'Contemporary dancer and choreographer from Montreal based in Boston.', 'youtube.com/chloedup', 'Weekdays', 10200, 4.45),
('Ravi', 'Menon', 'World Music', 'Tabla player and fusion musician blending Indian classical with jazz.', 'soundcloud.com/ravimenon', 'Weekends', 13600, 4.65),
('Tessa', 'Whitmore', 'Indie Rock', 'Lead vocalist of The Hollow Pines, known for powerful performances.', 'spotify.com/thehollowpines', 'Flexible', 9900, 4.35),
('Jake', 'Novak', 'Blues', 'Chicago-trained blues guitarist now resident in Somerville.', 'youtube.com/jakenovak', 'Weekends', 7400, 4.05),
('Aaliyah', 'Reeves', 'Soul', 'Soul and gospel-influenced vocalist with a powerful 4-octave range.', 'spotify.com/aaliyahreeves', 'Flexible', 20400, 4.85),
('Sam', 'Iwata', 'Electronic', 'Ambient electronic artist known for immersive soundscape sets.', 'soundcloud.com/samiwata', 'Weekends', 6800, 4.10),
('Grace', 'Abernathy', 'Folk', 'Appalachian folk revivalist performing with banjo and fiddle.', 'bandcamp.com/graceabernathy', 'Flexible', 5600, 3.95),
('Omar', 'Fofana', 'Afrobeats', 'Afrobeats artist bringing West African rhythms to Boston stages.', 'instagram.com/omarfofana', 'Weekends', 15900, 4.70),
('Lily', 'Chen', 'Classical', 'Concert pianist and Berklee graduate specializing in Romantic era works.', 'youtube.com/lilychen', 'Weekdays', 18700, 4.80),
('Travis', 'Holden', 'Country', 'Boston-based country singer with a traditional twang and modern edge.', 'spotify.com/travisholden', 'Flexible', 4900, 3.90),
('Serena', 'Adkins', 'Pop', 'High-energy pop performer known for elaborate stage productions.', 'instagram.com/serenapop', 'Weekends', 22000, 4.90),
('Kofi', 'Mensah', 'Jazz', 'Trumpet player and bandleader with residencies at top Boston jazz clubs.', 'spotify.com/kofimensah', 'Flexible', 14100, 4.65),
('Phoebe', 'Sterling', 'Indie Folk', 'Indie folk singer known for introspective lyrics and acoustic guitar.', 'bandcamp.com/phoebesterling', 'Weekends', 8300, 4.20),
('Dante', 'Ricci', 'Rock', 'Hard rock guitarist and frontman with a reputation for intense live shows.', 'youtube.com/dantericci', 'Flexible', 10700, 4.40),
('Mei', 'Zhou', 'Classical', 'Cellist and chamber musician based at New England Conservatory.', 'youtube.com/meizhou', 'Weekdays', 16500, 4.75),
('Anthony', 'Green', 'R&B', 'Smooth R&B artist blending neo-soul with modern trap influences.', 'spotify.com/anthonygreen', 'Weekends', 13200, 4.55),
('Isabelle', 'Laurent', 'Comedy', 'French-Canadian comedian performing bilingual stand-up.', 'instagram.com/isabellelaurent', 'Flexible', 7600, 4.15),
('Kobi', 'Asante', 'Reggae', 'Reggae and dancehall artist known for high-energy crowd interaction.', 'soundcloud.com/kobiasante', 'Weekends', 11800, 4.50),
('Nora', 'Flynn', 'Celtic', 'Traditional Irish uilleann piper and vocalist, Boston Celtic scene staple.', 'bandcamp.com/noraflynn', 'Flexible', 9100, 4.30),
('Elijah', 'Warren', 'Gospel', 'Gospel choir director and solo artist, brings full ensemble on request.', 'youtube.com/elijahwarren', 'Weekends', 17300, 4.80),
('Diana', 'Cruz', 'Latin Jazz', 'Latin jazz pianist and bandleader fusing Cuban rhythms with Boston flair.', 'spotify.com/dianacruz', 'Flexible', 15600, 4.70);


-- Venue (35 rows, OwnerID 1–35)
INSERT INTO Venue (Name, Capacity, Location, OwnerID) VALUES
('The Harbor Hall', 500, 'Boston, MA', 1),
('Reyes Rooftop', 150, 'Back Bay, MA', 2),
('Nakamura Center', 800, 'Cambridge, MA', 3),
('Brennan''s Tavern Stage', 200, 'Charlestown, MA', 4),
('Sullivan''s Grand Ballroom', 600, 'Boston, MA', 5),
('Fitzgerald Loft', 120, 'South End, MA', 6),
('Nguyen Arts Space', 300, 'Allston, MA', 7),
('Marconi Music Hall', 450, 'Somerville, MA', 8),
('Petrov Gallery & Events', 180, 'Jamaica Plain, MA', 9),
('Okafor Community Center', 700, 'Roxbury, MA', 10),
('Kowalski Courtyard', 250, 'Brighton, MA', 11),
('Andrade Cultural Center', 350, 'East Boston, MA', 12),
('Bernstein Black Box', 130, 'Cambridge, MA', 13),
('Tran Pavilion', 900, 'Quincy, MA', 14),
('O''Brien''s Live', 220, 'Allston, MA', 15),
('Chakraborty Event Loft', 160, 'Fenway, MA', 16),
('Rosenberg Amphitheater', 1200, 'Boston, MA', 17),
('MacLeod Social Club', 280, 'Dorchester, MA', 18),
('Ferreira Banquet Hall', 400, 'Newton, MA', 19),
('Huang Conference Center', 550, 'Waltham, MA', 20),
('Walsh Warehouse Stage', 320, 'Boston, MA', 21),
('Santos Speakeasy', 100, 'Back Bay, MA', 22),
('Kim Arts Collective', 190, 'Jamaica Plain, MA', 23),
('Patel Rooftop Terrace', 140, 'South End, MA', 24),
('Johansson Studio', 80, 'Cambridge, MA', 25),
('Moran Outdoor Venue', 2000, 'Boston Common, MA', 26),
('Delacroix Lounge', 110, 'Beacon Hill, MA', 27),
('Adeyemi Performing Arts', 500, 'Roxbury, MA', 28),
('Vasquez Event Space', 230, 'East Boston, MA', 29),
('Liang Innovation Hub', 400, 'Kendall Square, MA', 30),
('McCarthy Music Box', 175, 'Somerville, MA', 31),
('Esposito Hall', 650, 'North End, MA', 32),
('Cohen Creative Studio', 90, 'Cambridge, MA', 33),
('Oluwole Cultural Hall', 480, 'Dorchester, MA', 34),
('Yamamoto Event Center', 360, 'Brookline, MA', 35);


-- Event (40 rows)
INSERT INTO Event (Name, Date, Location, Description, Size, Category) VALUES
('Spring Jazz Night', '2026-04-18 19:00:00', 'Boston, MA', 'An evening of live jazz by the waterfront.', 300, 'Music'),
('Indie Rock Showcase', '2026-05-02 20:00:00', 'Cambridge, MA', 'Local indie bands compete for a record deal.', 140, 'Music'),
('Classical Gala', '2026-05-15 18:30:00', 'Cambridge, MA', 'A formal evening of classical piano and strings.', 600, 'Music'),
('Boston Food Festival', '2026-04-25 12:00:00', 'Boston, MA', 'Sample food from 50+ local restaurants and food trucks.', 2000, 'Food'),
('Comedy Night at O''Brien''s', '2026-05-08 21:00:00', 'Allston, MA', 'Stand-up comedy showcase featuring six local comedians.', 180, 'Comedy'),
('Hip-Hop Open Mic', '2026-04-30 20:00:00', 'Roxbury, MA', 'Open mic night celebrating Boston hip-hop talent.', 250, 'Music'),
('Charlestown Art Walk', '2026-05-20 14:00:00', 'Charlestown, MA', 'Guided walk through galleries and pop-up art installations.', 150, 'Art'),
('Electronic Dance Night', '2026-05-23 22:00:00', 'South End, MA', 'DJ showcase with local and regional electronic artists.', 320, 'Music'),
('Folk & Bluegrass Afternoon', '2026-06-01 15:00:00', 'Jamaica Plain, MA', 'Relaxed outdoor folk and bluegrass performances.', 200, 'Music'),
('Boston Fitness Expo', '2026-05-10 09:00:00', 'Newton, MA', 'Health and wellness expo with classes, demos, and vendors.', 500, 'Fitness'),
('R&B Soul Session', '2026-04-22 20:30:00', 'Dorchester, MA', 'Intimate R&B and soul performances in a lounge setting.', 120, 'Music'),
('Outdoor Film Screening', '2026-06-05 20:00:00', 'Boston Common, MA', 'Free outdoor screening of a classic film on the Common.', 1500, 'Film'),
('Afrobeats Dance Party', '2026-05-17 21:00:00', 'Allston, MA', 'High-energy Afrobeats DJ set with live percussionists.', 280, 'Music'),
('Cambridge Tech Meetup', '2026-04-29 18:30:00', 'Kendall Square, MA', 'Networking event for Boston-area tech professionals.', 200, 'Tech'),
('K-Pop Cover Night', '2026-05-25 19:00:00', 'Back Bay, MA', 'K-pop dance and vocal cover performances.', 160, 'Music'),
('Blues on the Waterfront', '2026-06-12 18:00:00', 'Boston, MA', 'Live blues performances along the Fort Point waterfront.', 350, 'Music'),
('South End Gallery Opening', '2026-05-06 18:00:00', 'South End, MA', 'Opening reception for a new contemporary art exhibition.', 130, 'Art'),
('World Music Festival', '2026-06-20 14:00:00', 'Roxbury, MA', 'Celebrating global music traditions with local world music acts.', 700, 'Music'),
('Beacon Hill Cocktail & Comedy', '2026-05-30 20:00:00', 'Beacon Hill, MA', 'Cocktail hour paired with short-form comedy performances.', 90, 'Comedy'),
('Summer Dance Showcase', '2026-06-07 19:00:00', 'Boston, MA', 'Contemporary and hip-hop dance showcase by local troupes.', 400, 'Dance'),
('Fenway Jazz Brunch', '2026-05-03 11:00:00', 'Fenway, MA', 'Sunday jazz brunch with live quartet and brunch menu.', 120, 'Music'),
('Gospel Sunday', '2026-04-26 13:00:00', 'Dorchester, MA', 'Uplifting gospel choir performance open to the community.', 450, 'Music'),
('Latin Jazz & Salsa Night', '2026-05-14 20:00:00', 'East Boston, MA', 'Live Latin jazz band and salsa dancing in East Boston.', 230, 'Music'),
('Brighton Comedy Crawl', '2026-05-16 19:00:00', 'Brighton, MA', 'Walking comedy night across three venues in Brighton.', 200, 'Comedy'),
('Somerville Block Party', '2026-06-14 15:00:00', 'Somerville, MA', 'Annual neighborhood block party with live music and food.', 650, 'Music'),
('Acoustic Sessions', '2026-05-28 19:30:00', 'Cambridge, MA', 'Intimate acoustic performances in a small studio setting.', 80, 'Music'),
('Celtic Music Night', '2026-04-24 20:00:00', 'Allston, MA', 'Traditional Irish and Celtic music night with dancing.', 200, 'Music'),
('Pop Showcase', '2026-06-18 20:00:00', 'Boston, MA', 'Emerging pop artists showcase their latest material.', 350, 'Music'),
('East Boston Food Tour', '2026-05-09 17:00:00', 'East Boston, MA', 'Guided food tour through the best East Boston eateries.', 100, 'Food'),
('Waltham Art & Tech Fair', '2026-05-31 10:00:00', 'Waltham, MA', 'Annual fair celebrating the intersection of art and technology.', 500, 'Art'),
('Reggae Beach Party', '2026-06-28 16:00:00', 'Quincy, MA', 'Outdoor reggae party with beach games and food vendors.', 800, 'Music'),
('North End Feast', '2026-07-04 13:00:00', 'North End, MA', 'Italian-American street festival with live music and food.', 600, 'Food'),
('Indie Film Night', '2026-05-21 19:00:00', 'Somerville, MA', 'Screening of three locally-produced indie short films.', 150, 'Film'),
('Fitness in the Park', '2026-06-21 08:00:00', 'Boston Common, MA', 'Free outdoor yoga, bootcamp, and wellness activities.', 300, 'Fitness'),
('Back Bay Jazz Walk', '2026-05-12 18:00:00', 'Back Bay, MA', 'Self-guided jazz listening experience across Back Bay venues.', 180, 'Music'),
('Brookline Chamber Music', '2026-06-04 19:00:00', 'Brookline, MA', 'Chamber music concert featuring string quartets and woodwinds.', 300, 'Music'),
('Hip-Hop Battle', '2026-05-22 20:00:00', 'Roxbury, MA', 'Freestyle rap battle tournament with cash prizes.', 350, 'Music'),
('Soul & Gospel Brunch', '2026-06-08 11:00:00', 'Dorchester, MA', 'Live soul and gospel music paired with a brunch buffet.', 200, 'Music'),
('Summer Pop-Up Market', '2026-06-27 12:00:00', 'Jamaica Plain, MA', 'Outdoor market with local vendors, live music, and food.', 400, 'Food'),
('Rock the Harbor', '2026-07-10 19:00:00', 'Boston, MA', 'Rock concert on the harbor featuring multiple local bands.', 500, 'Music');


-- Attendee (35 rows)
INSERT INTO Attendee (FName, LName, Email, DOB, Location) VALUES
('Nina', 'Torres', 'nina.torres@email.com', '1998-07-22', 'Boston, MA'),
('Ethan', 'Park', 'ethan.park@email.com', '2000-03-15', 'Cambridge, MA'),
('Zara', 'Ahmed', 'zara.ahmed@email.com', '1995-12-01', 'Somerville, MA'),
('Lucas', 'Ferreira', 'lucas.ferreira@email.com', '2001-08-19', 'Allston, MA'),
('Mia', 'Robinson', 'mia.robinson@email.com', '1997-04-30', 'Jamaica Plain, MA'),
('Connor', 'Walsh', 'connor.walsh@email.com', '1999-11-07', 'Charlestown, MA'),
('Aisha', 'Nwosu', 'aisha.nwosu@email.com', '1996-02-14', 'Roxbury, MA'),
('Tyler', 'Huang', 'tyler.huang@email.com', '2002-06-25', 'Back Bay, MA'),
('Sophia', 'Brennan', 'sophia.brennan@email.com', '1994-09-03', 'South End, MA'),
('Marcus', 'Ellis', 'marcus.ellis@email.com', '2000-01-17', 'Dorchester, MA'),
('Hannah', 'Kowalski', 'hannah.kowalski@email.com', '1998-05-28', 'Brighton, MA'),
('Jaylen', 'Brooks', 'jaylen.brooks@email.com', '1999-10-11', 'East Boston, MA'),
('Emma', 'Petersen', 'emma.petersen@email.com', '2001-03-23', 'Fenway, MA'),
('Amir', 'Hassan', 'amir.hassan@email.com', '1997-07-06', 'Cambridge, MA'),
('Grace', 'MacNeil', 'grace.macneil@email.com', '2003-12-14', 'Newton, MA'),
('Dominic', 'Vasquez', 'dominic.vasquez@email.com', '1996-08-29', 'Quincy, MA'),
('Priya', 'Anand', 'priya.anand@email.com', '2000-04-18', 'Waltham, MA'),
('Jordan', 'Lee', 'jordan.lee@email.com', '1995-06-08', 'Somerville, MA'),
('Kayla', 'Williams', 'kayla.williams@email.com', '2002-09-01', 'Boston, MA'),
('Ryan', 'O''Shea', 'ryan.oshea@email.com', '1998-02-22', 'Allston, MA'),
('Fatou', 'Diallo', 'fatou.diallo@email.com', '1997-11-30', 'Roxbury, MA'),
('Kevin', 'Nakamura', 'kevin.nakamura@email.com', '2001-07-14', 'Boston, MA'),
('Isabel', 'Cruz', 'isabel.cruz@email.com', '1999-04-05', 'East Boston, MA'),
('Ben', 'Shapiro', 'ben.shapiro@email.com', '2000-10-20', 'Cambridge, MA'),
('Destiny', 'Brown', 'destiny.brown@email.com', '1996-01-09', 'Dorchester, MA'),
('Liam', 'Byrne', 'liam.byrne@email.com', '2003-05-17', 'Charlestown, MA'),
('Yara', 'Khalil', 'yara.khalil@email.com', '1994-08-25', 'Back Bay, MA'),
('Miles', 'Thornton', 'miles.thornton@email.com', '2001-12-03', 'Jamaica Plain, MA'),
('Caitlin', 'Murphy', 'caitlin.murphy@email.com', '1998-03-16', 'Brighton, MA'),
('Jared', 'Oduya', 'jared.oduya@email.com', '1997-06-27', 'Fenway, MA'),
('Sabrina', 'Reyes', 'sabrina.reyes@email.com', '2002-09-09', 'South End, MA'),
('Theo', 'Andersen', 'theo.andersen@email.com', '1999-01-31', 'Somerville, MA'),
('Nkechi', 'Obi', 'nkechi.obi@email.com', '1995-07-12', 'Roxbury, MA'),
('Austin', 'Larson', 'austin.larson@email.com', '2000-11-24', 'Newton, MA'),
('Valeria', 'Moreno', 'valeria.moreno@email.com', '1997-04-02', 'Cambridge, MA');


-- Requests (60 rows, OrganizerID 1–35, VenueID 1–35)
INSERT INTO Requests (RequestName, Status, OrganizerID, VenueID) VALUES
('Spring Jazz Booking', 'Approved', 1, 1),
('Indie Rock Request', 'Approved', 2, 13),
('Classical Gala Venue', 'Approved', 3, 3),
('Food Festival Space', 'Approved', 4, 26),
('Comedy Night Booking', 'Approved', 5, 15),
('Hip-Hop Open Mic Space', 'Approved', 6, 10),
('Art Walk Coordination', 'Approved', 7, 4),
('Electronic Night DJ Venue', 'Approved', 8, 6),
('Folk Festival Grounds', 'Approved', 9, 9),
('Fitness Expo Hall', 'Approved', 10, 19),
('R&B Night Lounge', 'Approved', 11, 18),
('Film Screening Outdoor', 'Approved', 12, 26),
('Afrobeats Party Venue', 'Approved', 13, 7),
('Tech Meetup Space', 'Approved', 14, 30),
('K-Pop Night Hall', 'Approved', 15, 2),
('Blues Waterfront Stage', 'Approved', 16, 1),
('Gallery Opening Space', 'Approved', 17, 6),
('World Music Festival', 'Approved', 18, 28),
('Comedy Lounge Booking', 'Approved', 19, 27),
('Dance Showcase Stage', 'Approved', 20, 5),
('Fenway Jazz Brunch', 'Approved', 21, 16),
('Gospel Sunday Hall', 'Approved', 22, 34),
('Latin Jazz Night', 'Approved', 23, 12),
('Comedy Crawl Brighton', 'Approved', 24, 11),
('Block Party Stage', 'Approved', 25, 8),
('Acoustic Sessions Studio', 'Approved', 26, 25),
('Celtic Night Venue', 'Approved', 27, 15),
('Pop Showcase Hall', 'Approved', 28, 5),
('Food Tour East Boston', 'Approved', 29, 29),
('Art & Tech Fair Hall', 'Approved', 30, 20),
('Reggae Beach Party', 'Approved', 31, 14),
('North End Feast', 'Approved', 32, 32),
('Indie Film Screening', 'Approved', 33, 31),
('Fitness Park Event', 'Approved', 34, 26),
('Jazz Walk Request', 'Approved', 35, 2),
('Brookline Chamber Music', 'Pending', 1, 35),
('Hip-Hop Battle Arena', 'Pending', 2, 10),
('Soul Brunch Venue', 'Pending', 3, 18),
('Pop-Up Market Grounds', 'Pending', 4, 9),
('Rock Harbor Concert', 'Pending', 5, 1),
('Late Night Jazz Request', 'Pending', 6, 27),
('Spring Dance Festival', 'Pending', 7, 5),
('Waterfront Film Night', 'Pending', 8, 26),
('Blues Festival Request', 'Pending', 9, 17),
('Comedy Festival Booking', 'Pending', 10, 15),
('Acoustic Folk Night', 'Rejected', 11, 33),
('Summer Music Series', 'Rejected', 12, 17),
('Underground Electronic', 'Rejected', 13, 22),
('Poetry Slam Night', 'Rejected', 14, 13),
('DJ Battle Night', 'Rejected', 15, 8),
('Art Installation', 'Rejected', 16, 6),
('Open Mic Comedy', 'Pending', 17, 27),
('Chamber Concert', 'Pending', 18, 35),
('Rooftop Jazz', 'Pending', 19, 24),
('Hip-Hop Cypher', 'Pending', 20, 28),
('Indie Night', 'Pending', 21, 31),
('Folk Revival', 'Pending', 22, 9),
('Dance Pop Night', 'Pending', 23, 7),
('Gospel Choir Showcase', 'Pending', 24, 34),
('Latin Dance Night', 'Pending', 25, 12),
('World Beat Festival', 'Pending', 26, 28);


-- Hosts (40 rows — one venue per event)
INSERT INTO Hosts (VenueID, EventID) VALUES
(1, 1),
(13, 2),
(3, 3),
(26, 4),
(15, 5),
(10, 6),
(4, 7),
(6, 8),
(9, 9),
(19, 10),
(18, 11),
(26, 12),
(7, 13),
(30, 14),
(2, 15),
(1, 16),
(6, 17),
(28, 18),
(27, 19),
(5, 20),
(16, 21),
(34, 22),
(12, 23),
(11, 24),
(8, 25),
(25, 26),
(15, 27),
(5, 28),
(29, 29),
(20, 30),
(14, 31),
(32, 32),
(31, 33),
(26, 34),
(2, 35),
(35, 36),
(10, 37),
(18, 38),
(9, 39),
(1, 40);


-- Interests (70 rows — 2 per attendee on average)
INSERT INTO Interests (Interest, AttendeeID) VALUES
('Music', 1), ('Jazz', 1),
('Music', 2), ('Rock', 2),
('Classical', 3), ('Art', 3),
('Hip-Hop', 4), ('Music', 4),
('Music', 5), ('Dance', 5),
('Comedy', 6), ('Music', 6),
('Hip-Hop', 7), ('R&B', 7),
('Music', 8), ('K-Pop', 8),
('Classical', 9), ('Film', 9),
('Music', 10), ('Hip-Hop', 10),
('Music', 11), ('Fitness', 11),
('Music', 12), ('Hip-Hop', 12),
('Music', 13), ('Film', 13),
('Classical', 14), ('Tech', 14),
('Music', 15), ('Fitness', 15),
('Music', 16), ('Reggae', 16),
('Classical', 17), ('Tech', 17),
('Indie', 18), ('Folk', 18),
('Music', 19), ('Dance', 19),
('Rock', 20), ('Music', 20),
('Afrobeats', 21), ('Music', 21),
('Music', 22), ('Gospel', 22),
('Latin', 23), ('Music', 23),
('Comedy', 24), ('Music', 24),
('R&B', 25), ('Soul', 25),
('Folk', 26), ('Music', 26),
('Music', 27), ('Jazz', 27),
('Pop', 28), ('Music', 28),
('Food', 29), ('Music', 29),
('Art', 30), ('Tech', 30),
('Reggae', 31), ('Music', 31),
('Food', 32), ('Music', 32),
('Film', 33), ('Art', 33),
('Fitness', 34), ('Music', 34),
('Jazz', 35), ('Music', 35);
